name: CI Workflow

on:
  pull_request:
    branches:
      - 'main'

jobs:
  ci-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-pyspark.txt

      - name: Run tests with coverage
        run: |
          pytest --cov=src --cov-report=html
          
      - name: Upload Coverage HTML Report
        uses: actions/upload-artifact@v4.6.2
        with:
          name: coverage-html
          path: htmlcov
